// <auto-generated />
namespace SocialMedia.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedLikesCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedLikesCount));
        
        string IMigrationMetadata.Id
        {
            get { return "202011132012117_Added-LikesCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
